name: CI Pipeline (PR to Develop Branch)

on:
  pull_request:
    branches:
      - develop

jobs:
  call-template:
    uses: ecommerce-microservices-lab/ci-templates/.github/workflows/pr-to-develop.yaml@main
    with:
      projectKeyBase: ${{ github.repository }}
      projectNameBase: ${{ github.repository }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
